AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EC2KeyName:
    Type: String
    Description: Existing EC2 Key
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open ports 22 and 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '8883'
        ToPort: '8883'
        CidrIp: 0.0.0.0/0

  EC2InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: IoTWorkshopPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: Allow
                Action:
                  - "iam:*"
                  - "greengrass:*"
                  - "iot:*"
                  - "lambda:*"
                  - "iotanalytics:*"
                Resource: "*"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref EC2InstanceProfile
      KeyName: !Ref EC2KeyName
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      InstanceType: t2.micro
      ImageId: ami-04681a1dbd79675a5
      Tags:
      -
        Key: "Name"
        Value: "IoT-Workshop"
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            # elevate to super user
            sudo su
            # update yum
            yum -y update
            # download node
            curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
            # install node
            yum -y install nodejs
            # install git
            yum -y install git
            # create folder for files
            mkdir iot-workshop
            cd iot-workshop
            # clone greengrass-setup repo
            git clone https://github.com/retrofuturejosh/greengrass-setup.git
            cd greengrass-setup
            # run greengrass-setup
            npm install
            npm run create-group
            npm run start-greengrass
            cd /greengrass/ggc/core/
            ./greengrassd start
