AWSTemplateFormatVersion: 2010-09-09
Parameters:
  EC2KeyName:
    Type: String
    Description: Existing EC2 Key
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open ports 22 and 80
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '8883'
        ToPort: '8883'
        CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref EC2KeyName
      SecurityGroups:
      - !Ref InstanceSecurityGroup
      InstanceType: t2.micro
      ImageId: ami-04681a1dbd79675a5
      Tags:
      -
        Key: "Name"
        Value: "IoT-Workshop"
